// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Dispute struct {
	ID         int32            `json:"id"`
	EscrowID   pgtype.Int4      `json:"escrow_id"`
	Reason     string           `json:"reason"`
	Resolved   pgtype.Bool      `json:"resolved"`
	Resolution pgtype.Text      `json:"resolution"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type EscrowTransaction struct {
	ID             int32            `json:"id"`
	BuyerID        int32            `json:"buyer_id"`
	SellerID       int32            `json:"seller_id"`
	BitcoinAddress string           `json:"bitcoin_address"`
	Amount         pgtype.Numeric   `json:"amount"`
	Status         pgtype.Text      `json:"status"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
}
