// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateDisputes(ctx context.Context, arg CreateDisputesParams) (Dispute, error)
	CreateEscrowTransactions(ctx context.Context, arg CreateEscrowTransactionsParams) (EscrowTransaction, error)
	GetDisputes(ctx context.Context, id uuid.UUID) (Dispute, error)
	GetEscrowTransactions(ctx context.Context, id uuid.UUID) (EscrowTransaction, error)
	UpdateDisputes(ctx context.Context, arg UpdateDisputesParams) error
	UpdateEscrowTransactions(ctx context.Context, arg UpdateEscrowTransactionsParams) (EscrowTransaction, error)
}

var _ Querier = (*Queries)(nil)
