// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateEscrowTransactions(ctx context.Context, arg CreateEscrowTransactionsParams) (EscrowTransaction, error)
	GetEscrowTransactions(ctx context.Context, id int32) (EscrowTransaction, error)
	UpdateEscrowTransactions(ctx context.Context, arg UpdateEscrowTransactionsParams) error
}

var _ Querier = (*Queries)(nil)
